### ISSUE TITLE
Signing failing

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade-minimalci-sample#26]
@alexperovich , is the current build failure related to your changes - https://dnceng.visualstudio.com/public/_build/results?buildId=18584&view=logs

Can you take a look?

**Comment by chcosta** [comment]
Yeah, this repos triggers didn't get updated when we did the dotnet /dnceng account change. I just got admin permissions today, updated the triggers and noticed the failure while I was doing that

**Comment by jonfortescue** [comment]
This has been fixed.
