### ISSUE TITLE
Why the shipping package name is HelloWorld.1.0.0-dev.nupkg instead of HelloWorld.1.0.0-prerelease.nupkg?

### ISSUE THREAD

**Issue by ccic** [dotnet/arcade-minimalci-sample#546]
I used "Build.cmd -pack" and found the package name suffix is always "dev" instead of "prerelease". How can I replace "dev" with "prerelease"?

**Comment by jonfortescue** [comment]
@chcosta

**Comment by chcosta** [comment]
This is an Arcade convention for local developer builds - https://github.com/dotnet/arcade/blob/0c9b0442f2ce607a90615a7bfad4ead069150bc6/Documentation/CorePackages/Versioning.md#package-version
