### ISSUE TITLE
hi,😁

### ISSUE THREAD

**Issue by agood-boy** [dotnet/arcade-minimalci-sample#740]
Potential security breach. Username and password in URI in Url in file [/eng/common/sdl/push-gdn.ps1](https://github.com/dotnet/arcade-minimalci-sample/tree/master/eng/common/sdl/push-gdn.ps1)

You should recycle your credenttials immediately and move secrets to environment variables to prevent them being committed to GitHub.

Hope this will be helpful to you！

shout me a coffee ☕️ via [PayPal](https://www.paypal.me/agoodboy)

<a href="https://www.paypal.me/agoodboy">
  <img width="160" height="41" src="https://raw.githubusercontent.com/DWilliames/paddy-sketch-plugin/master/.images/paypal-badge.png" >
</a>

**Comment by jonfortescue** [comment]
no breach occurred; password is behind variable.
