### ISSUE TITLE
Add root level Build.cmd, build.sh

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade-minimalci-sample#8]
It's pretty standard in repos to have a root level entry point for building.  Note that dotnet/arcade has a root level Build.cmd, Restore.cmd, and Test.cmd (plus "sh" equivalents).  This repo should have those similar entry points (at least Build and Restore).

@jonfortescue

**Comment by jonfortescue** [comment]
@chcosta did this himself; thank you!
